FROM node:7.5.0 AS builder

ENV NPM_CONFIG_LOGLEVEL=warn

WORKDIR /usr/src/app

COPY package.json ./

RUN \
    npm set unsafe-perm true && \
    npm install

COPY ./assets/data ./assets/data
COPY ./assets/js ./assets/js
COPY ./assets/original_cards ./assets/original_cards
COPY ./assets/se ./assets/se
COPY ./assets/texture ./assets/texture

COPY ./client ./client

COPY ./public/Config.js ./public/

COPY ./server ./server

COPY ./test/lib ./test/lib
COPY ./test/src ./test/src
COPY ./test/SpecRunner.html ./test/

COPY ./gulpfile.js ./

RUN \
    apt update && \
    apt install graphicsmagick -y && \
    gm version

RUN npm run build

RUN rm -rf \
    ./assets/cards \
    ./assets/original_cards \
    ./assets/texture/ability \
    ./client \
    ./node_modules

#---

FROM node:7.5.0-slim

ENV NPM_CONFIG_LOGLEVEL=warn
ENV NODE_ENV=production

EXPOSE 3000
EXPOSE 16918

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
RUN npm install

# Add Tini, from https://github.com/krallin/tini#using-tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "-v", "-e", "143", "--"]

CMD ["node", "--harmony-async-await", "server/server.js"]
